modLoader="kotlinforforge" # We are forced to provide a mod loader even though we don't use it
loaderVersion="[${kotlinForgeVersion},)"

license = "GNU General Public License v3.0" # Do not change this
issueTrackerURL = "https://github.com/.../.../issues" # Change this to your issue tracker

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "Example Plugin"
authors = "${modAuthors}"
description = "${modDescription}"
logoFile = "assets/example/example.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlinForgeVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "lambda"
mandatory = true
versionRange = "[${lambdaVersion},)"
ordering = "NONE"
side = "CLIENT"
