modLoader="kotlinforforge"
loaderVersion="[${kotlinForgeVersion},)"
license = "GNU General Public License v3.0" # Do not change this
issueTrackerURL = "https://github.com/.../.../issues" # Change this to your issue tracker

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthors}"
description = "${modDescription}"
logoFile = "${modIcon}"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersionMin},${forgeVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersionMin},${minecraftVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlinForgeVersionMin},${kotlinForgeVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "lambda"
mandatory = true
versionRange = "[${lambdaVersion},)"
ordering = "NONE"
side = "CLIENT"
