modLoader = "kotlinforforge"
loaderVersion = "[${kotlinForgeVersion},)"
license = "GNU General Public License v3.0"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "Example"
authors = "${modAuthors}"
description = "${modDescription}"
logoFile = "assets/example/example.png"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "example.mixins.common.json"

[[dependencies.${modId}]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[${neoVersionMin},${neoVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[${minecraftVersionMin},${minecraftVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "kotlinforforge"
mandatory = true
type = "required"
versionRange = "[${kotlinForgeVersionMin},${kotlinForgeVersionMax}]"
ordering = "NONE"
side = "CLIENT"
